---

- hosts: ton_node
  become: true
  become_method: sudo
  any_errors_fatal: true
  vars_files:
    - vars/ton_node.yml
  roles:
    - ton_node_flush_db
  tags: [ "never", "flush" ]

- hosts: ton_node
  become: true
  become_method: sudo
  any_errors_fatal: true
  vars_files:
    - vars/ton_node.yml
  roles:
    - ton_node_genconfig
  tags: [ "never", "genconfig" ]

- hosts: ton_node
  become: true
  become_method: sudo
  gather_facts: true
  any_errors_fatal: true
  vars_files:
    - vars/ton_node.yml
    - vars/system.yml
    - vars/monitoring.yml
  pre_tasks:
    - name: Checking distribution
      fail:
        msg: "{{ ansible_distribution }} is not supported"
      when: ansible_distribution not in os_valid_distributions

    - name: Checking version of OS distribution
      fail:
        msg: "{{ ansible_distribution_version }} of {{ ansible_distribution }} is not supported"
      when: ansible_distribution_version is version_compare(os_minimum_versions[ansible_distribution], '<')
  roles:
    - system
    - ton_node_compile
    - ton_node_deploy
    - ton_node_genconfig
    - monitoring_agent
  tags: [ "basic" ]

- hosts: monitoring_server
  become: true
  become_method: sudo
  gather_facts: true
  any_errors_fatal: true
  vars_files:
    - vars/monitoring.yml
  roles:
    - monitoring_server
  tags: [ "never", "monitoring" ]